#!/bin/bash
# Create the "MultiVoice" launcher in the applications menu and on the desktop.
#
# The launcher is DYNAMIC: it records where this repo was when installed, but
# if you move the MultiVoice folder elsewhere it re-locates it automatically
# (searching inside $HOME). Only the launcher and the icon are fixed paths.
set -e

REPO="$(cd "$(dirname "$0")" && pwd)"
APP="multivoice"

ICON_DIR="$HOME/.local/share/icons"
BIN_DIR="$HOME/.local/bin"
APP_DIR="$HOME/.local/share/applications"
mkdir -p "$ICON_DIR" "$BIN_DIR" "$APP_DIR"

# Icon: copied to a fixed location, so it keeps working wherever the repo is.
cp "$REPO/assets/icon.png" "$ICON_DIR/$APP.png"

# Dynamic launcher: tries the recorded path first, then searches inside $HOME.
cat > "$BIN_DIR/$APP" <<EOF
#!/bin/bash
# MultiVoice dynamic launcher (generated by install.sh).
# Finds start.sh even if the MultiVoice folder is moved within \$HOME.
R="$REPO"
if [ ! -x "\$R/start.sh" ]; then
    R="\$(find "\$HOME" -maxdepth 5 -type d -name MultiVoice \
         -exec test -x "{}/start.sh" \; -print -quit 2>/dev/null)"
fi
if [ -n "\$R" ] && [ -x "\$R/start.sh" ]; then
    exec bash "\$R/start.sh"
fi
echo "MultiVoice: no se encontró la carpeta (buscada en \$HOME)."
read -r -p "Pulsa Enter para cerrar..."
EOF
chmod +x "$BIN_DIR/$APP"

cat > "$APP_DIR/$APP.desktop" <<EOF
[Desktop Entry]
Name=MultiVoice
Comment=Speak through a virtual microphone
Exec=$BIN_DIR/$APP
Icon=$ICON_DIR/$APP.png
Terminal=false
Type=Application
Categories=AudioVideo;Audio;
EOF
chmod +x "$APP_DIR/$APP.desktop"

for DESK in "$(xdg-user-dir DESKTOP 2>/dev/null)" "$HOME/Escritorio" "$HOME/Desktop"; do
  if [ -n "$DESK" ] && [ -d "$DESK" ]; then
    cp "$APP_DIR/$APP.desktop" "$DESK/$APP.desktop"
    chmod +x "$DESK/$APP.desktop"
    echo "✅ Launcher created on the desktop: $DESK/$APP.desktop"
    break
  fi
done

update-desktop-database "$APP_DIR" 2>/dev/null || true
echo "✅ MultiVoice is reachable from the app launcher."
echo "   (dynamic: it still works if you move the MultiVoice folder)"